version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

# mongo-express:
#   image: mongo-express
#   container_name: mongo-express
#   ports:
#     - "8081:8081"
#   environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#     ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
#     ME_CONFIG_MONGODB_SERVER: mongo
#   depends_on:
#     - mongo