version: '3.8'

services:
  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_KRAFT_CLUSTER_ID: kraft-cluster-id-123
      ALLOW_PLAINTEXT_LISTENER: yes

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

# mongo-express:
#   image: mongo-express
#   container_name: mongo-express
#   ports:
#     - "8081:8081"
#   environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#     ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
#     ME_CONFIG_MONGODB_SERVER: mongo
#   depends_on:
#     - mongo
